### ISSUE TITLE
libessp.so: undefined symbol: Status

### ISSUE THREAD

**Issue by IRomich** [Minege/eSSP#11]
Hello

I'm working with a device NV200 and get the following error:

PORT: /dev/ttyACM0
##/dev/ttyACM0##
Validator Found !
Encryption Setup
Firmware 0420 
Channels : 
Channel 1 :  10 RUB
Channel 2 :  50 RUB
Channel 3 :  100 RUB
Channel 4 :  500 RUB
Channel 5 :  1000 RUB
Channel 6 :  5000 RUB
Channel 7 :  0 
Channel 8 :  0 
Channel 9 :  0 
Channel 10 :  0 
Channel 11 :  0 
Channel 12 :  0 
Channel 13 :  0 
Channel 14 :  0 
Channel 15 :  0 
Channel 16 :  0 
Channel 17 :  0 
Channel 18 :  0 
Channel 19 :  0 
Channel 20 :  0
Payout
ERROR: Payout failed
Traceback (most recent call last):
  File "test.py", line 103, in <module>
    validator.do_actions()
  File "/usr/local/lib/python2.7/dist-packages/eSSP/eSSP.py", line 155, in do_actions
    self.essp.Status.SSP_get_response_data(
  File "/usr/lib/python2.7/ctypes/__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/local/lib/python2.7/dist-packages/eSSP/libessp.so: undefined symbol: Status

**Comment by Minege** [comment]
Hi,

Can you try to run it with Python3 ?
And also install the lib in a virtual env like that : `pip install git+https://github.com/Minege/eSSP` to get the latest version.

**Comment by IRomich** [comment]
I changed `self.essp.Status.SSP_get_response_data()` to `self.essp.ssp_get_response_data()` and it works.
Also I changed `self.essp.ssp6_set_route (self.sspC, self.actions_args ['routes_amount'], self.actions_args ['routes_currency'], Status.ENABLED.value)` to `self.essp.ssp6_set_route (self.sspC, self. actions_args ['routes_amount'], self.actions_args ['routes_currency'], Status.DISABLED.value)` to send bills to the storage.

**Comment by Minege** [comment]
Thanks for the help!
We'll update the repo accordingly.
