### ISSUE TITLE
essp not working

### ISSUE THREAD

**Issue by tarlesurendra** [Minege/eSSP#13]
Hello,

 we have nv200 device and trying to use your script and testing it on ubuntu 18 but we are getting below error

 python ex1.py
PORT: /dev/ttyS0
##/dev/ttyS0##
Segmentation fault (core dumped)

also please suggest any best solution for this

also help us for payout with nv200

thank you

**Comment by Minege** [comment]
Hello,

Can you please provide more informations about your system?

Thanks

**Comment by tarlesurendra** [comment]
Hello,

Thank you so much for your kind reply.
we are using nv200 device for our atm machine and we have installed Ubuntu 18.04.1 LTS on our system and nv200 device is connected serially that is /dev/ttSy0  to the system. we are trying to run your sample program code  that is "python ex1.py"  but its giving error as below

PORT: /dev/ttyS0
##/dev/ttyS0##
Segmentation fault (core dumped)

please help us to fix this problem and we would appraciated your help.
please let us know if you want anything more we are awaiting for your response.

thank you

**Comment by tarlesurendra** [comment]
Hello,

is there any solution for this?
we are waiting for the solution of above error essage

thank you

**Comment by Minege** [comment]
Hi,

To be able to find what's the problem, more information about your system
is needed.
Try sending the result of `uname - a` on your atm machine, for example.

Le jeu. 27 déc. 2018 à 05:08, tarlesurendra <notifications@github.com> a
écrit :

**Comment by tarlesurendra** [comment]
hello,

 below are the information of our system 

Linux nws-desktop 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

pleasee help us how to fix the issue with payout notes from machine nv200

**Comment by tasmail** [comment]
Hello,

please show an output of the following commands:

python
>>> import sys
>>> print(sys.version)

Did you install the library with pip?

Regards, 
Andrii

**Comment by tarlesurendra** [comment]
hello as per your instruction we have installed with pip and pleaes check
commands output

oot@nws-desktop:~# python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.version)
2.7.15rc1 (default, Nov 12 2018, 14:31:15)
[GCC 7.3.0]

**Comment by tasmail** [comment]
You are using python 2.7
Can you try it with python 3.x

**Comment by tarlesurendra** [comment]
can you tell me command to try ?

**Comment by tarlesurendra** [comment]
root@nws-desktop:~# python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.version)
3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0]
>>>

**Comment by tarlesurendra** [comment]
i am running your ex1.py file with python3 but getting below error

oot@nws-desktop:/opt/surendra/eSSP-master/examples# python3 ex1.py
Traceback (most recent call last):
  File "ex1.py", line 2, in <module>
    from eSSP.constants import Status
ModuleNotFoundError: No module named 'eSSP'

**Comment by Minege** [comment]
You have to install the eSSP module for python3.
Try `pip3 install eSSP6`.
If you can't execute pip3, try to install it :
`sudo apt-get install python3-pip`
And then try to install the eSSP module again.
Now, you can try to execute the example code.
