### ISSUE TITLE
Remove dead code

### ISSUE THREAD

**Issue by 0xjac** [Minege/eSSP#2]
There is some commented code on the following lines:
- [L337-L338](https://github.com/Minege/eSSP/blob/f39458621b68005cc51c6bc1bd2fb8b51d8532e2/eSSP/eSSP.py#L337-L338)
- [L346-L347](https://github.com/Minege/eSSP/blob/f39458621b68005cc51c6bc1bd2fb8b51d8532e2/eSSP/eSSP.py#L346-L347)
- [L354-L355](https://github.com/Minege/eSSP/blob/f39458621b68005cc51c6bc1bd2fb8b51d8532e2/eSSP/eSSP.py#L354-L355)
- [L362-L363](https://github.com/Minege/eSSP/blob/f39458621b68005cc51c6bc1bd2fb8b51d8532e2/eSSP/eSSP.py#L362-L363)

(This should be taken care of when solving #1)

**Comment by Minege** [comment]
Fixed
