### ISSUE TITLE
Use an actions queue instead of a string

### ISSUE THREAD

**Issue by 0xjac** [Minege/eSSP#3]
Use a `Queue` rather than a string to handle the `actions` may be more adapted  ([L118](https://github.com/Minege/eSSP/blob/f39458621b68005cc51c6bc1bd2fb8b51d8532e2/eSSP/eSSP.py#L118))

It's clearer and you can get rid of `ACTION_SIZE` and `i` logic.

Here is an example on how you would handle it:
```python
from queue import Queue


def __init__(self, *args, **kwargs):
    self.actions = Queue()

def do_actions(self):
    while not self.actions.empty():
        action = self.actions.get()
        # do something with action
        
def add_action(action):
    self.actions.put(action)  # instead of self.actions += action

```
 
> This is also much easier to make thread-proof in the future, when you have ATMs with octo-cores... 😁

**Comment by tshabs** [comment]
Note on using Queue, it might be better to use six.moves Queue (for py2 & py3 compatibility).

eg: 
https://github.com/Simonefardella/escposprinter/commit/4e13ee25cdfaeb85a1dc7bb2d5716cb32a88fdb7

**Comment by 0xjac** [comment]
I wasn't aware you needed compatibility with Python 2. In that case, yes use `six.moves`.

Using `Enum` in #4 may also be problematic. I would write a simple `Enum` class for Python 2 in this case.
